### ISSUE TITLE
Q: I understand the add a cat demo, how do I build non-image related cards?

### ISSUE THREAD

**Issue by marks** [Scarygami/mirror-api#10]
Hi there - First off, this API/interface emulator is great! Thanks so much.

I've played around with it by setting up my own app engine app/etc. and have gotten the hang of taking a picture and adding a cat/sepia tone. I'm trying to figure out how I could build an app that would not have to do with images but would instead let the user say something (i.e. "what is the price of X") and the text would make it to the app and the app could return a card such as a picture, html, etc.

Any pointers of how to get started on something like this within the emulator would be much appreciated.

Thanks in advance

**Comment by Scarygami** [comment]
Sharing text messages with a service is something that isn't possible in the API at the moment.

There is an issue in the official Mirror API bug tracker, that covers this use case: https://code.google.com/p/google-glass-api/issues/detail?id=6

One possible workaround for now is to send a card with a REPLY option to the users timeline. If the user chooses Reply he can talk any text that is then sent to your service so you can react on it.

**Comment by marks** [comment]
Thank you @Scarygami (and sorry to reopen this ticket) but do you have an example of such a card with a reply option to the timeline that sends the reply text back to the app/server the card came from?

**Comment by Scarygami** [comment]
Nope, not yet.

But some links from the official documentation:
https://developers.google.com/glass/subscriptions#reply
https://developers.google.com/glass/menu-items#built-in-menu-items
