### ISSUE TITLE
API Explorer redirects and does not show the mirror API

### ISSUE THREAD

**Issue by pat-dalberg** [Scarygami/mirror-api#13]
When I try to use the API Explorer to send cards per the Unofficial Mirror API Emulator Documentation I am getting redirected like is being reported here 

https://developers.google.com/explorer-help/forum?place=msg%2Fgoogle-apis-explorer-users%2FQpy9WDdNmrw%2F9_aZnZiQoEwJ

I try to go to 

https://mmirroremulator.appspot.com/_ah/api/explorer

and get redirected to

https://developers.google.com/apis-explorer/?base=https://mmirroremulator.appspot.com/_ah/api#p/

where I see APIs Discovery Service v1, but I don't see the mirror API. 

I have not modified any code, just added the appropriate codes to client_secrets.json per the docs. 

Has anyone else run into this? Has anyone else run into this and resolved it?

Thanks in Advance.

Pat

**Comment by robin-karlsson** [comment]
I experienced the exact same behavior, but I was successful in working with the api from the clients I tried with. I worked with the .net client and the test pages for the emulator. Worked like a charm!

**Comment by Scarygami** [comment]
There still seems to be an issue with listing the APIs in the API Explorer (cc @dhermes)

You can access the API directly via this URL (adding the mirror/v1/ to the URL):
https://developers.google.com/apis-explorer/?base=https://mmirroremulator.appspot.com/_ah/api#p/mirror/v1/

**Comment by dhermes** [comment]
Yes, I suspect it may be something to do with the name `mirror` itself. I'll try to triage with the folks who maintain the APIs Explorer.

**Comment by pat-dalberg** [comment]
Thanks Gerwin, using the URL you provided makes the mirror API available as in the docs. I can move forward like this now.

**Comment by dhermes** [comment]
@Scarygami @pat-dalberg that workaround will work just fine for now; sorry for the inconvenience.

We've identified the issue causing this. Let me know if this is urgent/causing larger hassles and I can try to escalate the fix to get done quicker.

Thanks for reporting it.

**Comment by pat-dalberg** [comment]
@dhermes - thanks for the response. The workaround will suffice for me going forward. I'll leave it to @Scarygami to request an escalation if he feels that is needed, and would only suggest that the docs get updated to call out the URL workaround. My thanks again to the both of you.

**Comment by Scarygami** [comment]
I've updated the API Explorer URL in the Readme, don't really see this as an urgent issue.
