### ISSUE TITLE
Installation Notes and Edit Suggestions

### ISSUE THREAD

**Issue by johnfontaine** [Scarygami/mirror-api#16]
I've been working to setup the environment on localhost and on app engine.  A couple of notes:

1- When installing on a local server I think you need to update the base_url parameter in utils.py to be "localhost:8080" instead of base_url = "https://" + appname + ".appspot.com"
1. Instead of editing the app.yaml one could use the -A parameter. 
   # cd mirror_api_server
   # appcfg.py -A myapp update ./

**Comment by Scarygami** [comment]
I've had some problems running cloud endpoints on localhost because the python api client seems to require https for calls, that's why I left the base_url to point to server.

**Comment by johnfontaine** [comment]
Thanks that does explain some other things I've noticed between localhost and running on appspot.

**Comment by Scarygami** [comment]
I also see actually editing the app.yaml to change the application name much cleaner, since it makes sure that the app is called the same in your local dev environment, and people might be using the AppEngine launcher to deploy as opposed to command line, which always uses the name from app.yaml
