### ISSUE TITLE
The emulator doesn't work anymor

### ISSUE THREAD

**Issue by dhbismuth** [Scarygami/mirror-api#18]
Hello ! 

First thanks for your great work on sharing your expertise and knowledge on the google glass interface. 
Since this morning the emulator is not responding anymore on two emulator I know. Do you know why ? Maybe Google has changed something in its mirror API ? 

Many thanks,

Dhbismuth

**Comment by Scarygami** [comment]
The emulator doesn't depend on the real Mirror API so it isn't affected by Google making changes.

What error are you seeing. Do you see any errors in the AppEngine console?

**Comment by dhbismuth** [comment]
Thanks for the quick answer. The AppEngine console looks fine (I can push cards to the emulator) but the Glass screen  (OK Glass) doesn't appear anymore due to the Google Sign-in which don't respond. 

## Below an extract of the debug console : 

Error setting up Channel: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>500 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>

<h1>Error: Server Error</h1>

<h2>The server encountered an error and could not complete your request.<p>If the problem persists, please <A HREF="http://code.google.com/appengine/community.html">report</A> your problem and mention this error message and the query that caused it.</h2>

<h2></h2>

</body></html>

**Comment by Scarygami** [comment]
Hmmm, it might be that you exhausted your free AppEngine quota for channels (which is limited to 100 a day).

In the https://appengine.google.com/dashboard for your application, check the "Channels created" number at the bottom. If you have been testing a lot this might be the problem.
![screenshot 2013-06-06 at 16 21 37](https://f.cloud.github.com/assets/809528/618434/98e8b62e-ceb4-11e2-8e3a-00dd5db6e434.png)

Only solution would be to enable billing for your application, channels come at the price of $0.01/100 channels so not really a significant amount.

**Comment by dhbismuth** [comment]
I have 0 at this level : 
![image](https://f.cloud.github.com/assets/2641552/618498/0cef7746-ceb6-11e2-9da9-8f4bd582a242.png)

**Comment by Scarygami** [comment]
Can you check the logs, there should be an error in there somewhere: https://appengine.google.com/logs

The emulator that I have hosted for my own testing is working without problems.

**Comment by dhbismuth** [comment]
Hi Gerwin,

The emulator is functionning again. After research, the problem comes from Google+ signin and synchronisations with services. 

Many thanks for your support and for the code !
