### ISSUE TITLE
Failed to initialize client library. Discovery document not found.

### ISSUE THREAD

**Issue by vasind** [Scarygami/mirror-api#22]
Hi,

I followed the steps given in the Readme documentation. After creating my application https://go-glass.appspot.com/test/ , i launched in Chrome as well as Firefox. But it throws "Error 500: Internal Server Error
service.js (line 133)
{"error": {"message": "Failed to initialize client library. Discovery document not found.", "code": 500}}" . I tried a lot by creating many applications https://besideglass.appspot.com/test/ still problem persists. :(  Please find below request header and URL.

curl 'https://go-glass.appspot.com/test/connect?state=33XP0VZEY3K26ZIK7VS804W2QKLHSC1I&gplus_id=116386942049558404665' -X POST -H 'Host: go-glass.appspot.com' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:23.0) Gecko/20100101 Firefox/23.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/octet-stream; charset=utf-8' -H 'Referer: https://go-glass.appspot.com/test/' -H 'Cookie: mirror_session=eyJfc2lkIjoidE5NT3dBc2RyV282Y05CWWVuSlZLNSJ9|1381926884|d52bf46449e1cb9914965067c6ead9afb3500a43; GCSCU_651938521824_H3=C=651938521824.apps.googleusercontent.com:S=b6a94056e8627be4406e6e6dd58710421527096a.1GiJehyvtzKf_DHG.6011:I=1381926111:X=1382012511; GCSCE_651938521824_S3=C=651938521824.apps.googleusercontent.com:S=0bfa6203e19ec19ec1d7988d706819fade42c508..8346:I=1381926867:X=1381930467; G_AUTHUSER_S3=0'

**Comment by Scarygami** [comment]
https://go-glass.appspot.com/_ah/api/discovery/v1/apis is returning a 404 which means your endpoints haven't been initialized correctly. Check your logs at https://appengine.google.com for errors to narrow down the problem.

Mostly this problem happens when the endpoints-proto-datastore library hasn't been included correctly with the git submodule init/update steps from the readme.

**Comment by vasind** [comment]
Ah !! Yes. You are correct. I made a mistake by downloading this project as a ZIP rather than cloning via git shell. Thanks for your quick reply !!! :)
