### ISSUE TITLE
Error: origin_mismatch

### ISSUE THREAD

**Issue by naddaf** [Scarygami/mirror-api#8]
Hi.

I followed the instructions and app was successfully uploaded and deployed. However, when I access <myapp>,appspot.com/test/ and click on Sign In button and enter my credentials, I get an error:

Error: origin_mismatch

Any suggestion?
Thanks
Ali.

**Comment by Scarygami** [comment]
Have you added https://yourapp.appspot.com/ to the allowed Javascript origins in the [API Console](https://code.google.com/apis/console/)?

And if you have entered this you have to make sure to also visit the https version of your site and not the http version.

**Comment by naddaf** [comment]
I guess the issue was https vs http, it works now.

Thanks.
